### PR TITLE
fix missing rmw installation and update docs

### LINKED ISSUE #66: Missing RMW cyclone dds install in sim container
**Describe the bug**

sim container failed to rebuild on WSL due to missing rmw_cyclonedds_cpp package. Once fixed it ran fine again.

**To Reproduce**

try to open dev container in vscode. If using docker desktop, you can see the error logs. If not, just check that the container died using docker cli.

**Expected behavior**

sim container should build and run fine for anyone.

**Screenshots**

**Operating System**
 - [x] Windows WSL
- [ ] Mac with no VM
- [ ] Mac with VM
- [ ] Linux

**Additional context**

Don't know how but I think it was running fine on my linux laptop, but not sure if my stuff was up to date.

### PR DESCRIPTION
**Pull request by Jquinny**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it relates to an open issue, be sure to link to that issue. Ensure that you add a label to the PR describing the type of change (if the issue does not have one already for whatever reason).

just a quick fix for a broken sim container due to missing rmw cyclone installation. updated documentation for new members to do the `export ...` stuff in their containers if they are running windows.

closes #66 

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](../docs/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] Any changes to main have been merged into my branch

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Jquinny** [comment]
I need to figure out why merge checks are blocking. Will test with a changed file in src/ to see if the checks skipping when no changes in src/ is causing the blockage.

**Comment by Jquinny** [comment]
looks like having the linters be required status checks on the main branch means they MUST run, even if no changes to src/ directory have been made. We might just have to eat it and have the checks run even when no changes to src/ directory have been made (this should be fine since the linter actions are set to run checks only on changed files I believe).

**Comment by Jquinny** [comment]
> I need to figure out why merge checks are blocking. Will test with a changed file in src/ to see if the checks skipping when no changes in src/ is causing the blockage.

looks like having the linters be required status checks on the main branch means they MUST run, even if no changes to src/ directory have been made. We might just have to eat it and have the checks run even when no changes to src/ directory have been made (this should be fine since the linter actions are set to run checks only on changed files I believe).

**Review by RyderCatonio — APPROVED** [review]
lg2m

**Pull request merged**
